//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  hero: Hero;
  heroConnection: HeroConnection;
  mision: Mision;
  misionConnection: MisionConnection;
  servicios: Servicios;
  serviciosConnection: ServiciosConnection;
  testimonios: Testimonios;
  testimoniosConnection: TestimoniosConnection;
  cta: Cta;
  ctaConnection: CtaConnection;
  contacto: Contacto;
  contactoConnection: ContactoConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHeroArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHeroConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HeroFilter>;
};


export type QueryMisionArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryMisionConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<MisionFilter>;
};


export type QueryServiciosArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryServiciosConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ServiciosFilter>;
};


export type QueryTestimoniosArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTestimoniosConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TestimoniosFilter>;
};


export type QueryCtaArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryCtaConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<CtaFilter>;
};


export type QueryContactoArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryContactoConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContactoFilter>;
};

export type DocumentFilter = {
  hero?: InputMaybe<HeroFilter>;
  mision?: InputMaybe<MisionFilter>;
  servicios?: InputMaybe<ServiciosFilter>;
  testimonios?: InputMaybe<TestimoniosFilter>;
  cta?: InputMaybe<CtaFilter>;
  contacto?: InputMaybe<ContactoFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Hero | Mision | Servicios | Testimonios | Cta | Contacto | Folder;

export type Hero = Node & Document & {
  __typename?: 'Hero';
  titulo_1?: Maybe<Scalars['String']['output']>;
  titulo_2?: Maybe<Scalars['String']['output']>;
  titulo_3?: Maybe<Scalars['String']['output']>;
  subtitulo?: Maybe<Scalars['String']['output']>;
  boton_form?: Maybe<Scalars['String']['output']>;
  imagen_hero?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type HeroFilter = {
  titulo_1?: InputMaybe<StringFilter>;
  titulo_2?: InputMaybe<StringFilter>;
  titulo_3?: InputMaybe<StringFilter>;
  subtitulo?: InputMaybe<StringFilter>;
  boton_form?: InputMaybe<StringFilter>;
  imagen_hero?: InputMaybe<ImageFilter>;
};

export type HeroConnectionEdges = {
  __typename?: 'HeroConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Hero>;
};

export type HeroConnection = Connection & {
  __typename?: 'HeroConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HeroConnectionEdges>>>;
};

export type Mision = Node & Document & {
  __typename?: 'Mision';
  etiqueta?: Maybe<Scalars['String']['output']>;
  titulo?: Maybe<Scalars['String']['output']>;
  subtitulo_naranja?: Maybe<Scalars['String']['output']>;
  descripcion?: Maybe<Scalars['String']['output']>;
  boton?: Maybe<Scalars['String']['output']>;
  imagen?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type MisionFilter = {
  etiqueta?: InputMaybe<StringFilter>;
  titulo?: InputMaybe<StringFilter>;
  subtitulo_naranja?: InputMaybe<StringFilter>;
  descripcion?: InputMaybe<StringFilter>;
  boton?: InputMaybe<StringFilter>;
  imagen?: InputMaybe<ImageFilter>;
};

export type MisionConnectionEdges = {
  __typename?: 'MisionConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Mision>;
};

export type MisionConnection = Connection & {
  __typename?: 'MisionConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<MisionConnectionEdges>>>;
};

export type ServiciosServicio_1 = {
  __typename?: 'ServiciosServicio_1';
  emoji?: Maybe<Scalars['String']['output']>;
  nombre?: Maybe<Scalars['String']['output']>;
  descripcion?: Maybe<Scalars['String']['output']>;
};

export type ServiciosServicio_2 = {
  __typename?: 'ServiciosServicio_2';
  emoji?: Maybe<Scalars['String']['output']>;
  nombre?: Maybe<Scalars['String']['output']>;
  descripcion?: Maybe<Scalars['String']['output']>;
};

export type ServiciosServicio_3 = {
  __typename?: 'ServiciosServicio_3';
  emoji?: Maybe<Scalars['String']['output']>;
  nombre?: Maybe<Scalars['String']['output']>;
  descripcion?: Maybe<Scalars['String']['output']>;
};

export type Servicios = Node & Document & {
  __typename?: 'Servicios';
  titulo_seccion?: Maybe<Scalars['String']['output']>;
  servicio_1?: Maybe<ServiciosServicio_1>;
  servicio_2?: Maybe<ServiciosServicio_2>;
  servicio_3?: Maybe<ServiciosServicio_3>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ServiciosServicio_1Filter = {
  emoji?: InputMaybe<StringFilter>;
  nombre?: InputMaybe<StringFilter>;
  descripcion?: InputMaybe<StringFilter>;
};

export type ServiciosServicio_2Filter = {
  emoji?: InputMaybe<StringFilter>;
  nombre?: InputMaybe<StringFilter>;
  descripcion?: InputMaybe<StringFilter>;
};

export type ServiciosServicio_3Filter = {
  emoji?: InputMaybe<StringFilter>;
  nombre?: InputMaybe<StringFilter>;
  descripcion?: InputMaybe<StringFilter>;
};

export type ServiciosFilter = {
  titulo_seccion?: InputMaybe<StringFilter>;
  servicio_1?: InputMaybe<ServiciosServicio_1Filter>;
  servicio_2?: InputMaybe<ServiciosServicio_2Filter>;
  servicio_3?: InputMaybe<ServiciosServicio_3Filter>;
};

export type ServiciosConnectionEdges = {
  __typename?: 'ServiciosConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Servicios>;
};

export type ServiciosConnection = Connection & {
  __typename?: 'ServiciosConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ServiciosConnectionEdges>>>;
};

export type TestimoniosTestimonio_1 = {
  __typename?: 'TestimoniosTestimonio_1';
  nombre?: Maybe<Scalars['String']['output']>;
  texto?: Maybe<Scalars['String']['output']>;
  foto?: Maybe<Scalars['String']['output']>;
};

export type TestimoniosTestimonio_2 = {
  __typename?: 'TestimoniosTestimonio_2';
  nombre?: Maybe<Scalars['String']['output']>;
  texto?: Maybe<Scalars['String']['output']>;
  foto?: Maybe<Scalars['String']['output']>;
};

export type TestimoniosTestimonio_3 = {
  __typename?: 'TestimoniosTestimonio_3';
  nombre?: Maybe<Scalars['String']['output']>;
  texto?: Maybe<Scalars['String']['output']>;
  foto?: Maybe<Scalars['String']['output']>;
};

export type Testimonios = Node & Document & {
  __typename?: 'Testimonios';
  testimonio_1?: Maybe<TestimoniosTestimonio_1>;
  testimonio_2?: Maybe<TestimoniosTestimonio_2>;
  testimonio_3?: Maybe<TestimoniosTestimonio_3>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type TestimoniosTestimonio_1Filter = {
  nombre?: InputMaybe<StringFilter>;
  texto?: InputMaybe<StringFilter>;
  foto?: InputMaybe<ImageFilter>;
};

export type TestimoniosTestimonio_2Filter = {
  nombre?: InputMaybe<StringFilter>;
  texto?: InputMaybe<StringFilter>;
  foto?: InputMaybe<ImageFilter>;
};

export type TestimoniosTestimonio_3Filter = {
  nombre?: InputMaybe<StringFilter>;
  texto?: InputMaybe<StringFilter>;
  foto?: InputMaybe<ImageFilter>;
};

export type TestimoniosFilter = {
  testimonio_1?: InputMaybe<TestimoniosTestimonio_1Filter>;
  testimonio_2?: InputMaybe<TestimoniosTestimonio_2Filter>;
  testimonio_3?: InputMaybe<TestimoniosTestimonio_3Filter>;
};

export type TestimoniosConnectionEdges = {
  __typename?: 'TestimoniosConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Testimonios>;
};

export type TestimoniosConnection = Connection & {
  __typename?: 'TestimoniosConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TestimoniosConnectionEdges>>>;
};

export type Cta = Node & Document & {
  __typename?: 'Cta';
  titulo_1?: Maybe<Scalars['String']['output']>;
  titulo_2?: Maybe<Scalars['String']['output']>;
  boton?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type CtaFilter = {
  titulo_1?: InputMaybe<StringFilter>;
  titulo_2?: InputMaybe<StringFilter>;
  boton?: InputMaybe<StringFilter>;
};

export type CtaConnectionEdges = {
  __typename?: 'CtaConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Cta>;
};

export type CtaConnection = Connection & {
  __typename?: 'CtaConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<CtaConnectionEdges>>>;
};

export type Contacto = Node & Document & {
  __typename?: 'Contacto';
  telefono?: Maybe<Scalars['String']['output']>;
  email?: Maybe<Scalars['String']['output']>;
  direccion?: Maybe<Scalars['String']['output']>;
  footer_texto?: Maybe<Scalars['String']['output']>;
  copyright?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ContactoFilter = {
  telefono?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
  direccion?: InputMaybe<StringFilter>;
  footer_texto?: InputMaybe<StringFilter>;
  copyright?: InputMaybe<StringFilter>;
};

export type ContactoConnectionEdges = {
  __typename?: 'ContactoConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Contacto>;
};

export type ContactoConnection = Connection & {
  __typename?: 'ContactoConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ContactoConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateHero: Hero;
  createHero: Hero;
  updateMision: Mision;
  createMision: Mision;
  updateServicios: Servicios;
  createServicios: Servicios;
  updateTestimonios: Testimonios;
  createTestimonios: Testimonios;
  updateCta: Cta;
  createCta: Cta;
  updateContacto: Contacto;
  createContacto: Contacto;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateHeroArgs = {
  relativePath: Scalars['String']['input'];
  params: HeroMutation;
};


export type MutationCreateHeroArgs = {
  relativePath: Scalars['String']['input'];
  params: HeroMutation;
};


export type MutationUpdateMisionArgs = {
  relativePath: Scalars['String']['input'];
  params: MisionMutation;
};


export type MutationCreateMisionArgs = {
  relativePath: Scalars['String']['input'];
  params: MisionMutation;
};


export type MutationUpdateServiciosArgs = {
  relativePath: Scalars['String']['input'];
  params: ServiciosMutation;
};


export type MutationCreateServiciosArgs = {
  relativePath: Scalars['String']['input'];
  params: ServiciosMutation;
};


export type MutationUpdateTestimoniosArgs = {
  relativePath: Scalars['String']['input'];
  params: TestimoniosMutation;
};


export type MutationCreateTestimoniosArgs = {
  relativePath: Scalars['String']['input'];
  params: TestimoniosMutation;
};


export type MutationUpdateCtaArgs = {
  relativePath: Scalars['String']['input'];
  params: CtaMutation;
};


export type MutationCreateCtaArgs = {
  relativePath: Scalars['String']['input'];
  params: CtaMutation;
};


export type MutationUpdateContactoArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactoMutation;
};


export type MutationCreateContactoArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactoMutation;
};

export type DocumentUpdateMutation = {
  hero?: InputMaybe<HeroMutation>;
  mision?: InputMaybe<MisionMutation>;
  servicios?: InputMaybe<ServiciosMutation>;
  testimonios?: InputMaybe<TestimoniosMutation>;
  cta?: InputMaybe<CtaMutation>;
  contacto?: InputMaybe<ContactoMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  hero?: InputMaybe<HeroMutation>;
  mision?: InputMaybe<MisionMutation>;
  servicios?: InputMaybe<ServiciosMutation>;
  testimonios?: InputMaybe<TestimoniosMutation>;
  cta?: InputMaybe<CtaMutation>;
  contacto?: InputMaybe<ContactoMutation>;
};

export type HeroMutation = {
  titulo_1?: InputMaybe<Scalars['String']['input']>;
  titulo_2?: InputMaybe<Scalars['String']['input']>;
  titulo_3?: InputMaybe<Scalars['String']['input']>;
  subtitulo?: InputMaybe<Scalars['String']['input']>;
  boton_form?: InputMaybe<Scalars['String']['input']>;
  imagen_hero?: InputMaybe<Scalars['String']['input']>;
};

export type MisionMutation = {
  etiqueta?: InputMaybe<Scalars['String']['input']>;
  titulo?: InputMaybe<Scalars['String']['input']>;
  subtitulo_naranja?: InputMaybe<Scalars['String']['input']>;
  descripcion?: InputMaybe<Scalars['String']['input']>;
  boton?: InputMaybe<Scalars['String']['input']>;
  imagen?: InputMaybe<Scalars['String']['input']>;
};

export type ServiciosServicio_1Mutation = {
  emoji?: InputMaybe<Scalars['String']['input']>;
  nombre?: InputMaybe<Scalars['String']['input']>;
  descripcion?: InputMaybe<Scalars['String']['input']>;
};

export type ServiciosServicio_2Mutation = {
  emoji?: InputMaybe<Scalars['String']['input']>;
  nombre?: InputMaybe<Scalars['String']['input']>;
  descripcion?: InputMaybe<Scalars['String']['input']>;
};

export type ServiciosServicio_3Mutation = {
  emoji?: InputMaybe<Scalars['String']['input']>;
  nombre?: InputMaybe<Scalars['String']['input']>;
  descripcion?: InputMaybe<Scalars['String']['input']>;
};

export type ServiciosMutation = {
  titulo_seccion?: InputMaybe<Scalars['String']['input']>;
  servicio_1?: InputMaybe<ServiciosServicio_1Mutation>;
  servicio_2?: InputMaybe<ServiciosServicio_2Mutation>;
  servicio_3?: InputMaybe<ServiciosServicio_3Mutation>;
};

export type TestimoniosTestimonio_1Mutation = {
  nombre?: InputMaybe<Scalars['String']['input']>;
  texto?: InputMaybe<Scalars['String']['input']>;
  foto?: InputMaybe<Scalars['String']['input']>;
};

export type TestimoniosTestimonio_2Mutation = {
  nombre?: InputMaybe<Scalars['String']['input']>;
  texto?: InputMaybe<Scalars['String']['input']>;
  foto?: InputMaybe<Scalars['String']['input']>;
};

export type TestimoniosTestimonio_3Mutation = {
  nombre?: InputMaybe<Scalars['String']['input']>;
  texto?: InputMaybe<Scalars['String']['input']>;
  foto?: InputMaybe<Scalars['String']['input']>;
};

export type TestimoniosMutation = {
  testimonio_1?: InputMaybe<TestimoniosTestimonio_1Mutation>;
  testimonio_2?: InputMaybe<TestimoniosTestimonio_2Mutation>;
  testimonio_3?: InputMaybe<TestimoniosTestimonio_3Mutation>;
};

export type CtaMutation = {
  titulo_1?: InputMaybe<Scalars['String']['input']>;
  titulo_2?: InputMaybe<Scalars['String']['input']>;
  boton?: InputMaybe<Scalars['String']['input']>;
};

export type ContactoMutation = {
  telefono?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
  direccion?: InputMaybe<Scalars['String']['input']>;
  footer_texto?: InputMaybe<Scalars['String']['input']>;
  copyright?: InputMaybe<Scalars['String']['input']>;
};

export type HeroPartsFragment = { __typename: 'Hero', titulo_1?: string | null, titulo_2?: string | null, titulo_3?: string | null, subtitulo?: string | null, boton_form?: string | null, imagen_hero?: string | null };

export type MisionPartsFragment = { __typename: 'Mision', etiqueta?: string | null, titulo?: string | null, subtitulo_naranja?: string | null, descripcion?: string | null, boton?: string | null, imagen?: string | null };

export type ServiciosPartsFragment = { __typename: 'Servicios', titulo_seccion?: string | null, servicio_1?: { __typename: 'ServiciosServicio_1', emoji?: string | null, nombre?: string | null, descripcion?: string | null } | null, servicio_2?: { __typename: 'ServiciosServicio_2', emoji?: string | null, nombre?: string | null, descripcion?: string | null } | null, servicio_3?: { __typename: 'ServiciosServicio_3', emoji?: string | null, nombre?: string | null, descripcion?: string | null } | null };

export type TestimoniosPartsFragment = { __typename: 'Testimonios', testimonio_1?: { __typename: 'TestimoniosTestimonio_1', nombre?: string | null, texto?: string | null, foto?: string | null } | null, testimonio_2?: { __typename: 'TestimoniosTestimonio_2', nombre?: string | null, texto?: string | null, foto?: string | null } | null, testimonio_3?: { __typename: 'TestimoniosTestimonio_3', nombre?: string | null, texto?: string | null, foto?: string | null } | null };

export type CtaPartsFragment = { __typename: 'Cta', titulo_1?: string | null, titulo_2?: string | null, boton?: string | null };

export type ContactoPartsFragment = { __typename: 'Contacto', telefono?: string | null, email?: string | null, direccion?: string | null, footer_texto?: string | null, copyright?: string | null };

export type HeroQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HeroQuery = { __typename?: 'Query', hero: { __typename: 'Hero', id: string, titulo_1?: string | null, titulo_2?: string | null, titulo_3?: string | null, subtitulo?: string | null, boton_form?: string | null, imagen_hero?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type HeroConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HeroFilter>;
}>;


export type HeroConnectionQuery = { __typename?: 'Query', heroConnection: { __typename?: 'HeroConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HeroConnectionEdges', cursor: string, node?: { __typename: 'Hero', id: string, titulo_1?: string | null, titulo_2?: string | null, titulo_3?: string | null, subtitulo?: string | null, boton_form?: string | null, imagen_hero?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type MisionQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type MisionQuery = { __typename?: 'Query', mision: { __typename: 'Mision', id: string, etiqueta?: string | null, titulo?: string | null, subtitulo_naranja?: string | null, descripcion?: string | null, boton?: string | null, imagen?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type MisionConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<MisionFilter>;
}>;


export type MisionConnectionQuery = { __typename?: 'Query', misionConnection: { __typename?: 'MisionConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'MisionConnectionEdges', cursor: string, node?: { __typename: 'Mision', id: string, etiqueta?: string | null, titulo?: string | null, subtitulo_naranja?: string | null, descripcion?: string | null, boton?: string | null, imagen?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ServiciosQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ServiciosQuery = { __typename?: 'Query', servicios: { __typename: 'Servicios', id: string, titulo_seccion?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, servicio_1?: { __typename: 'ServiciosServicio_1', emoji?: string | null, nombre?: string | null, descripcion?: string | null } | null, servicio_2?: { __typename: 'ServiciosServicio_2', emoji?: string | null, nombre?: string | null, descripcion?: string | null } | null, servicio_3?: { __typename: 'ServiciosServicio_3', emoji?: string | null, nombre?: string | null, descripcion?: string | null } | null } };

export type ServiciosConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ServiciosFilter>;
}>;


export type ServiciosConnectionQuery = { __typename?: 'Query', serviciosConnection: { __typename?: 'ServiciosConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ServiciosConnectionEdges', cursor: string, node?: { __typename: 'Servicios', id: string, titulo_seccion?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, servicio_1?: { __typename: 'ServiciosServicio_1', emoji?: string | null, nombre?: string | null, descripcion?: string | null } | null, servicio_2?: { __typename: 'ServiciosServicio_2', emoji?: string | null, nombre?: string | null, descripcion?: string | null } | null, servicio_3?: { __typename: 'ServiciosServicio_3', emoji?: string | null, nombre?: string | null, descripcion?: string | null } | null } | null } | null> | null } };

export type TestimoniosQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type TestimoniosQuery = { __typename?: 'Query', testimonios: { __typename: 'Testimonios', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, testimonio_1?: { __typename: 'TestimoniosTestimonio_1', nombre?: string | null, texto?: string | null, foto?: string | null } | null, testimonio_2?: { __typename: 'TestimoniosTestimonio_2', nombre?: string | null, texto?: string | null, foto?: string | null } | null, testimonio_3?: { __typename: 'TestimoniosTestimonio_3', nombre?: string | null, texto?: string | null, foto?: string | null } | null } };

export type TestimoniosConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TestimoniosFilter>;
}>;


export type TestimoniosConnectionQuery = { __typename?: 'Query', testimoniosConnection: { __typename?: 'TestimoniosConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'TestimoniosConnectionEdges', cursor: string, node?: { __typename: 'Testimonios', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, testimonio_1?: { __typename: 'TestimoniosTestimonio_1', nombre?: string | null, texto?: string | null, foto?: string | null } | null, testimonio_2?: { __typename: 'TestimoniosTestimonio_2', nombre?: string | null, texto?: string | null, foto?: string | null } | null, testimonio_3?: { __typename: 'TestimoniosTestimonio_3', nombre?: string | null, texto?: string | null, foto?: string | null } | null } | null } | null> | null } };

export type CtaQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type CtaQuery = { __typename?: 'Query', cta: { __typename: 'Cta', id: string, titulo_1?: string | null, titulo_2?: string | null, boton?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type CtaConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<CtaFilter>;
}>;


export type CtaConnectionQuery = { __typename?: 'Query', ctaConnection: { __typename?: 'CtaConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'CtaConnectionEdges', cursor: string, node?: { __typename: 'Cta', id: string, titulo_1?: string | null, titulo_2?: string | null, boton?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ContactoQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ContactoQuery = { __typename?: 'Query', contacto: { __typename: 'Contacto', id: string, telefono?: string | null, email?: string | null, direccion?: string | null, footer_texto?: string | null, copyright?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ContactoConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContactoFilter>;
}>;


export type ContactoConnectionQuery = { __typename?: 'Query', contactoConnection: { __typename?: 'ContactoConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ContactoConnectionEdges', cursor: string, node?: { __typename: 'Contacto', id: string, telefono?: string | null, email?: string | null, direccion?: string | null, footer_texto?: string | null, copyright?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const HeroPartsFragmentDoc = gql`
    fragment HeroParts on Hero {
  __typename
  titulo_1
  titulo_2
  titulo_3
  subtitulo
  boton_form
  imagen_hero
}
    `;
export const MisionPartsFragmentDoc = gql`
    fragment MisionParts on Mision {
  __typename
  etiqueta
  titulo
  subtitulo_naranja
  descripcion
  boton
  imagen
}
    `;
export const ServiciosPartsFragmentDoc = gql`
    fragment ServiciosParts on Servicios {
  __typename
  titulo_seccion
  servicio_1 {
    __typename
    emoji
    nombre
    descripcion
  }
  servicio_2 {
    __typename
    emoji
    nombre
    descripcion
  }
  servicio_3 {
    __typename
    emoji
    nombre
    descripcion
  }
}
    `;
export const TestimoniosPartsFragmentDoc = gql`
    fragment TestimoniosParts on Testimonios {
  __typename
  testimonio_1 {
    __typename
    nombre
    texto
    foto
  }
  testimonio_2 {
    __typename
    nombre
    texto
    foto
  }
  testimonio_3 {
    __typename
    nombre
    texto
    foto
  }
}
    `;
export const CtaPartsFragmentDoc = gql`
    fragment CtaParts on Cta {
  __typename
  titulo_1
  titulo_2
  boton
}
    `;
export const ContactoPartsFragmentDoc = gql`
    fragment ContactoParts on Contacto {
  __typename
  telefono
  email
  direccion
  footer_texto
  copyright
}
    `;
export const HeroDocument = gql`
    query hero($relativePath: String!) {
  hero(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HeroParts
  }
}
    ${HeroPartsFragmentDoc}`;
export const HeroConnectionDocument = gql`
    query heroConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HeroFilter) {
  heroConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HeroParts
      }
    }
  }
}
    ${HeroPartsFragmentDoc}`;
export const MisionDocument = gql`
    query mision($relativePath: String!) {
  mision(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...MisionParts
  }
}
    ${MisionPartsFragmentDoc}`;
export const MisionConnectionDocument = gql`
    query misionConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: MisionFilter) {
  misionConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...MisionParts
      }
    }
  }
}
    ${MisionPartsFragmentDoc}`;
export const ServiciosDocument = gql`
    query servicios($relativePath: String!) {
  servicios(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ServiciosParts
  }
}
    ${ServiciosPartsFragmentDoc}`;
export const ServiciosConnectionDocument = gql`
    query serviciosConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ServiciosFilter) {
  serviciosConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ServiciosParts
      }
    }
  }
}
    ${ServiciosPartsFragmentDoc}`;
export const TestimoniosDocument = gql`
    query testimonios($relativePath: String!) {
  testimonios(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TestimoniosParts
  }
}
    ${TestimoniosPartsFragmentDoc}`;
export const TestimoniosConnectionDocument = gql`
    query testimoniosConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TestimoniosFilter) {
  testimoniosConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TestimoniosParts
      }
    }
  }
}
    ${TestimoniosPartsFragmentDoc}`;
export const CtaDocument = gql`
    query cta($relativePath: String!) {
  cta(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...CtaParts
  }
}
    ${CtaPartsFragmentDoc}`;
export const CtaConnectionDocument = gql`
    query ctaConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: CtaFilter) {
  ctaConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...CtaParts
      }
    }
  }
}
    ${CtaPartsFragmentDoc}`;
export const ContactoDocument = gql`
    query contacto($relativePath: String!) {
  contacto(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ContactoParts
  }
}
    ${ContactoPartsFragmentDoc}`;
export const ContactoConnectionDocument = gql`
    query contactoConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ContactoFilter) {
  contactoConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ContactoParts
      }
    }
  }
}
    ${ContactoPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      hero(variables: HeroQueryVariables, options?: C): Promise<{data: HeroQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HeroQueryVariables, query: string}> {
        return requester<{data: HeroQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HeroQueryVariables, query: string}, HeroQueryVariables>(HeroDocument, variables, options);
      },
    heroConnection(variables?: HeroConnectionQueryVariables, options?: C): Promise<{data: HeroConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HeroConnectionQueryVariables, query: string}> {
        return requester<{data: HeroConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HeroConnectionQueryVariables, query: string}, HeroConnectionQueryVariables>(HeroConnectionDocument, variables, options);
      },
    mision(variables: MisionQueryVariables, options?: C): Promise<{data: MisionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MisionQueryVariables, query: string}> {
        return requester<{data: MisionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MisionQueryVariables, query: string}, MisionQueryVariables>(MisionDocument, variables, options);
      },
    misionConnection(variables?: MisionConnectionQueryVariables, options?: C): Promise<{data: MisionConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MisionConnectionQueryVariables, query: string}> {
        return requester<{data: MisionConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MisionConnectionQueryVariables, query: string}, MisionConnectionQueryVariables>(MisionConnectionDocument, variables, options);
      },
    servicios(variables: ServiciosQueryVariables, options?: C): Promise<{data: ServiciosQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServiciosQueryVariables, query: string}> {
        return requester<{data: ServiciosQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServiciosQueryVariables, query: string}, ServiciosQueryVariables>(ServiciosDocument, variables, options);
      },
    serviciosConnection(variables?: ServiciosConnectionQueryVariables, options?: C): Promise<{data: ServiciosConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServiciosConnectionQueryVariables, query: string}> {
        return requester<{data: ServiciosConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServiciosConnectionQueryVariables, query: string}, ServiciosConnectionQueryVariables>(ServiciosConnectionDocument, variables, options);
      },
    testimonios(variables: TestimoniosQueryVariables, options?: C): Promise<{data: TestimoniosQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimoniosQueryVariables, query: string}> {
        return requester<{data: TestimoniosQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimoniosQueryVariables, query: string}, TestimoniosQueryVariables>(TestimoniosDocument, variables, options);
      },
    testimoniosConnection(variables?: TestimoniosConnectionQueryVariables, options?: C): Promise<{data: TestimoniosConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimoniosConnectionQueryVariables, query: string}> {
        return requester<{data: TestimoniosConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimoniosConnectionQueryVariables, query: string}, TestimoniosConnectionQueryVariables>(TestimoniosConnectionDocument, variables, options);
      },
    cta(variables: CtaQueryVariables, options?: C): Promise<{data: CtaQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CtaQueryVariables, query: string}> {
        return requester<{data: CtaQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CtaQueryVariables, query: string}, CtaQueryVariables>(CtaDocument, variables, options);
      },
    ctaConnection(variables?: CtaConnectionQueryVariables, options?: C): Promise<{data: CtaConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CtaConnectionQueryVariables, query: string}> {
        return requester<{data: CtaConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: CtaConnectionQueryVariables, query: string}, CtaConnectionQueryVariables>(CtaConnectionDocument, variables, options);
      },
    contacto(variables: ContactoQueryVariables, options?: C): Promise<{data: ContactoQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactoQueryVariables, query: string}> {
        return requester<{data: ContactoQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactoQueryVariables, query: string}, ContactoQueryVariables>(ContactoDocument, variables, options);
      },
    contactoConnection(variables?: ContactoConnectionQueryVariables, options?: C): Promise<{data: ContactoConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactoConnectionQueryVariables, query: string}> {
        return requester<{data: ContactoConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactoConnectionQueryVariables, query: string}, ContactoConnectionQueryVariables>(ContactoConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  