[build]
  publish = "."
  command = "npm install && npx @tinacms/cli@latest build"

[build.environment]
  NODE_VERSION = "18"
  TINA_PUBLIC_CLIENT_ID = "40561aba-f9f7-4e3d-a8fa-d0149e35ca4b"
  TINA_TOKEN = "7e3f66ae4163da82066dca9e0c46999c7ee217cb"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' 'unsafe-eval' 'unsafe-inline' https: data: blob:; img-src 'self' data: blob: https:; connect-src 'self' https://*.tina.io https://*.tinajs.io wss://*.tina.io https:;"