'use client';
import React, { useState } from 'react';
import type { AICreditMovement, AIUsageRow } from '../00-shared/types';
import { EmptyState, StatCard, StatusPill } from '../00-shared/ui';
import styles from './ai.module.css';

export type AIConfigView = { enabled:boolean; ready:boolean; provider:string; model:string; credits:number; usedThisMonth:number; estimatedProviderCost:number; estimatedSale:number; estimatedMargin:number; lowBalanceAt?:number; sellPricePer1000?:number };

export function AIPremiumModule({ config, usage, ledger, onConfigure, onTopUp, onToggleEnabled, onTest }: { config:AIConfigView; usage:AIUsageRow[]; ledger?:AICreditMovement[]; onConfigure?:()=>void; onTopUp?:(credits:number)=>void; onToggleEnabled?:(enabled:boolean)=>void; onTest?:()=>void }) {
  const [topup,setTopup]=useState(10000);
  return <div className={styles.page}>
    <section className={styles.hero}><div><div className={styles.title}><span>🧠</span><div><h2>FlowZap AI</h2><p>Módulo premium opcional. El bot normal sigue funcionando sin IA.</p></div></div><div className={styles.badges}><StatusPill tone="premium">Premium</StatusPill><StatusPill tone={config.ready?'success':'warning'}>{config.ready?'Listo':'Configuración pendiente'}</StatusPill></div></div><label className={styles.switch}><input type="checkbox" checked={config.enabled} onChange={(e)=>onToggleEnabled?.(e.target.checked)}/><span>IA habilitada</span></label></section>
    <div className={styles.stats}><StatCard icon="🪙" label="Créditos disponibles" value={config.credits.toLocaleString()} sub="Saldo actual"/><StatCard icon="📉" label="Utilizados este mes" value={config.usedThisMonth.toLocaleString()} sub="Consumo acumulado"/><StatCard icon="🏭" label="Costo proveedor" value={`$${config.estimatedProviderCost.toFixed(2)}`} sub="Solo administración"/><StatCard icon="💰" label="Venta estimada" value={`$${config.estimatedSale.toFixed(2)}`} sub="Según tu tarifa"/><StatCard icon="📈" label="Margen estimado" value={`$${config.estimatedMargin.toFixed(2)}`} sub="Venta - costo"/></div>
    <div className={styles.columns}><section className={styles.card}><header><div><h3>Proveedor y modelo</h3><p>Configuración segura por empresa</p></div><button onClick={onConfigure}>Configurar</button></header><div className={styles.provider}><span>Proveedor</span><strong>{config.provider || 'Sin configurar'}</strong><span>Modelo</span><strong>{config.model || '—'}</strong></div><button className={styles.test} onClick={onTest}>🧪 Probar conexión IA</button></section><section className={styles.card}><header><div><h3>Recargar créditos</h3><p>Wallet prepago</p></div></header><div className={styles.topups}>{[1000,5000,10000,50000].map((n)=><button key={n} className={topup===n?styles.selected:''} onClick={()=>setTopup(n)}>{n.toLocaleString()}</button>)}</div><button className={styles.primary} onClick={()=>onTopUp?.(topup)}>+ Agregar {topup.toLocaleString()} créditos</button><small>En producción, esta acción debe pasar por facturación/ledger y permisos administrativos.</small></section></div>
    <section className={styles.card}><header><div><h3>Consumo IA</h3><p>Detalle de llamadas, tokens y créditos</p></div></header><div className={styles.tableWrap}><table><thead><tr><th>Fecha</th><th>Proveedor / modelo</th><th>Tokens E/S</th><th>Créditos</th><th>Costo</th><th>Origen</th></tr></thead><tbody>{usage.length?usage.map((u)=><tr key={u.id}><td>{u.createdAt}</td><td><strong>{u.provider}</strong><small>{u.model}</small></td><td>{u.inputTokens||0} / {u.outputTokens||0}</td><td><strong>{u.credits||0}</strong></td><td>${Number(u.estimatedCost||0).toFixed(4)}</td><td>{u.source || 'flow'}</td></tr>):<tr><td colSpan={6}><EmptyState icon="🧠" title="Aún no hay consumo IA"/></td></tr>}</tbody></table></div></section>
    {ledger && <section className={styles.card}><header><div><h3>Movimientos de créditos</h3><p>Historial auditable de la wallet</p></div></header><div className={styles.ledger}>{ledger.map((m)=><div key={m.id}><span>{m.createdAt}</span><strong className={m.amount>=0?styles.plus:styles.minus}>{m.amount>=0?'+':''}{m.amount.toLocaleString()}</strong><span>{m.reference || m.type}</span><b>{m.balanceAfter.toLocaleString()}</b></div>)}</div></section>}
  </div>;
}
